apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sunny-developer
  name: vscode-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vscode-rolebinding
  namespace: sunny-developer
subjects:
- kind: ServiceAccount
  name: vscode-user
  namespace: sunny-developer
roleRef:
  kind: Role
  name: vscode-role
  apiGroup: rbac.authorization.k8s.io

